# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AdtraceExample-Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for AdtraceExample-Swift
  pod 'Adtrace', path: "../../"
  
end
